### ISSUE TITLE
一直显示这个错误

### ISSUE THREAD

**Issue by FangTangJing** [anjia0532/elastalert-docker#11]
![image](https://user-images.githubusercontent.com/24773663/147734835-f45fcf95-427d-46fc-81b4-c5ccb10aabb7.png)

**Comment by anjia0532** [comment]
版本问题？

**Comment by FangTangJing** [comment]
修改了dingtalk_alert.py脚本和rules_config.yaml莫名其妙好了，也不知道是不是改对了
