### ISSUE TITLE
elastalert elasticsearch密码

### ISSUE THREAD

**Issue by zhangkun123456** [anjia0532/elastalert-docker#14]
dock部署elastalert连接elasticsearch时候密码用a123456可以启动成功。如果使用这种密码X@a#i&i47，docker容器启动的时候，会刷报错，waitting for elasticsearch。elastalert是不是不支持含有特殊字符的es密码

**Comment by anjia0532** [comment]
https://github.com/anjia0532/elastalert-docker/blob/98899818c408883e925aee44ac4f2d8dd5f4ad94/docker-entrypoint.sh#L115

用的basic auth，你把@去掉或者做下转义，应该就可以

**Comment by zhangkun123456** [comment]
谢谢
