### ISSUE TITLE
启动后py报错，环境变量没有配置port

### ISSUE THREAD

**Issue by Zyawn** [anjia0532/elastalert-docker#15]
![image](https://user-images.githubusercontent.com/29703380/221129476-b91bf1cc-1d65-49f3-9507-c929d64918d6.png)

**Comment by anjia0532** [comment]
<html>
<body>


Env var | Elastalert config var | Default
-- | -- | --



</body>
</html>
<html>
<body>


ELASTICSEARCH_PORT | es_port | 9200
-- | -- | --



</body>
</html>

**Comment by Zyawn** [comment]
不是，我一开始配置了ELASTICSEARCH_PORT，报了这个错，后来我打算不配置让他默认9200，也报这个错

**Comment by anjia0532** [comment]
telnet 看看

**Comment by Zyawn** [comment]
在同一服务器、同一容器网络下部署的
![image](https://user-images.githubusercontent.com/29703380/221500531-434ad9f2-ec39-457f-8b28-812e71510799.png)

**Comment by anjia0532** [comment]
运行容器（比如上来就sleep 10000），然后bash进去看看

`cat ${ELASTALERT_HOME}/config.yaml` 
`echo ${ES_PORT}`

![报错](https://user-images.githubusercontent.com/29703380/221129476-b91bf1cc-1d65-49f3-9507-c929d64918d6.png)

看报错是，int(os.env("ES_PORT),conf('es.port')) 报错，也就是 `int('tcp://ip:9200') ` 报错。至于为啥端口是 `tcp://ip:9200` 而不是 `9200`

**Comment by Zyawn** [comment]
普通的容器部署和在k8s中部署是不是不太一样

**Comment by Zyawn** [comment]
可以了，在k8s中部署会自动注入同名的环境变量
