### ISSUE TITLE
使用微信告警发生获取访问_token失败（qyapi.weixin.qq.com）这是为什么

### ISSUE THREAD

**Issue by alerll** [anjia0532/elastalert-docker#16]
ERROR:root:Error while running alert WeChatAlerter: get access_token failed , stacktrace:HTTPSConnectionPool(host='qyapi.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/gettoken?corpid=ww5afd903541d35bad&corpsecret=UikmL5UHdmH093GGYhG0xDL9LvLIMqanQckU7_2uP7o (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb548ada470>: Failed to establish a new connection: [Errno 110] Operation timed out',))

**Comment by anjia0532** [comment]
你最好是把这个issues删了，重新提一个，并且把你的corpsecret重置下，贴出的信息里，包含了敏感信息（corpid和corpsecret），防止别人拿到后，恶意使用。

 你百度下 `Max retries exceeded with url` 不就知道了？

简单来说,要么网络有问题，要么设置的告警策略太敏感，导致短时间内大量报警刷微信接口，微信给你拦截了。
