### ISSUE TITLE
如果使用企业微信群机器人是否可以直接调整

### ISSUE THREAD

**Issue by use-epoll** [anjia0532/elastalert-docker#17]
如题  如果要对接企业微信群里的机器人  是否可以在企业微信那个模块上直接改

**Comment by anjia0532** [comment]
目前支持的是 [发送应用消息 /cgi-bin/message/send](https://developer.work.weixin.qq.com/document/path/90236)
你说的是 [群机器人 /cgi-bin/webhook/send](https://developer.work.weixin.qq.com/document/path/99110) ?
欢迎提PR，参考 https://github.com/anjia0532/elastalert-docker/blob/master/elastalert_modules/wechat_qiye_alert.py 新建一个modules 比如叫 wechat_qiye_robot_alert.py

**Comment by use-epoll** [comment]
对是你所说的那个api    /cgi-bin/webhook/send ? 这个的

**Comment by anjia0532** [comment]
欢迎 提 PR
