### ISSUE TITLE
能否增加一个通用webhook

### ISSUE THREAD

**Issue by bogeit** [anjia0532/elastalert-docker#6]
你好，如题，现在是你这边给出钉钉和企微，用的人就只能用这两个固定的webhook，我想能不能增加一个通用的webhook，我自己来准备一个过滤清洗转发的web服务来接收，再转到钉钉，企微，飞书等平台上去，这样灵活程度更高。

**Comment by anjia0532** [comment]
官方有实现

https://github.com/Yelp/elastalert/pull/3042/files
