### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by miaojanson** [anjia0532/elastalert-docker#7]
运行elastalert,在shell窗口，显示时间是对的。但是在elastalert_status里面时区-8了，rule就在es里面找前8个小时的日志进行filter。这个问题在哪里设置可以解决，谢谢

**Comment by anjia0532** [comment]
`运行elastalert,在shell窗口，显示时间是对的` 这说明镜像时区是对的
`但是在elastalert_status里面时区-8了` es的日期就是0时区
`rule就在es里面找前8个小时的日志进行filter。这个问题在哪里设置可以解决，谢谢` 在kibana你能查出来的querydsl放到filter里就行
